image:
  name: node:24-alpine


stages:
  - docs


pages:

  stage: docs

  tags:
    - docker


  before_script:

    # VitePress 需要 git 获取更新时间
    - apk add --no-cache git

    # 启用 pnpm
    - corepack enable


  script:

    # 安装依赖
    - pnpm install --frozen-lockfile

    # 构建文档
    - pnpm docs:build

    # GitLab Pages 要求目录名必须是 public
    - mv docs/.vitepress/dist public


  artifacts:

    paths:
      - public