image: node:24-alpine

stages:
  - docs

pages:
  stage: docs
  tags:
    - docker

  before_script:
    - apk add --no-cache git
    - corepack enable

  script:
    - pnpm install --frozen-lockfile
    - pnpm docs:build
    - mv docs/.vitepress/dist public

  artifacts:
    paths:
      - public